#!/usr/bin/bash

# function to exit with status 1
# the debhomedev is unmounted first
# the rc code is passed as first parameter, no exit on 0, exit on 1, 2, 3..
# second parameter is the error string
exitonerror() {
	# test rc code
	if test $1 -ne 0; then
		# display error string
		echo "return code: $1"
		echo "$2"

		# log error
		log "$2"
		exit 1;
	fi
}

# function to setup subversion link to the new path
# the new user must already exist
# the owner.group of the /mnt directory must
# be set to new user
# check the repository exists and then check/set the link
# to point to it.
# parameters: setupreppository
# 		$1 CURUSER  (non root)
#		$2 svnpath | debhomepath
#		$3 link  (/mnt/svn/ | /mnt/debhome)
#		$4 debhome | svn device which may not be necessary
#########################################################
setuprepository() {
	# check new user exists
	/usr/bin/getent passwd "$1" > /dev/null 2>&1 
	exitonerror $? "new user $1 does not exist"

	# makelive now makes directories /mnt/debhome
	# and /mnt/svn to access svn and debhome.
	# makelive delets these directories

	# set ownership of /mnt to robert:robert
	/usr/bin/chown $1:$1 /mnt

	# check that there is not a directory with the name of the link.
	# remove it or fail
	# if debhome or svn is a directory remove the directory
	# so a link can be made.
	# test -d link gives true if link points to a directory.
	# hence test for directory must be
	# if file exists and is not a link and is a directory
	if test -e "${3}" && test ! -L "${3}" && test -d "${3}"; then
		echo "${3} is a directory, removing .."
		rmdir -v "${3}"
		exitonerror $? "Could not remove directory ${3}"
	fi

	# check that repository can be found
	# at the path
	if test -d "$2"; then
		# path exists now check the link
		if test -L "$3"; then
			# the link exists
			# check where it points to
			LINKPATH=`ls -l $3 | cut -d " " -f11`

			# now check if link points to svn | debhome path
			if test "${LINKPATH}" != "$2"; then
				# link must be changed
				rm -vf "$3"
				exitonerror $? "could not remove link $3"
				# make the new link
				sudo -u $1 ln -s "$2" "$3"
				exitonerror $? "could not make the link $3"
			fi

		else
			# there is no link
			# make the link
			sudo -u $1 ln -s "$2" "$3"
			exitonerror $? "could not make the link $3"
		fi
		# subversion | debhome exists and link is correct
		echo "old link -> ${LINKPATH} new link -> $2"

	else
		# full path does not exist to repository
		# try and mount debhome | svn device
		echo "repository does not exist at $2"
		echo "will try and mount device $4"
		
		test -d "/mnt/$4" || sudo -u $1 mkdir "/mnt/$4"
		exitonerror $? "could not make directory /mnt/$4"

		# mount the device if not mounted
		# check where it is mounted
		# should be on /mnt/$4
		findmnt --source LABEL="$4"
		if test $? -eq 0; then
			# device is mounted
			# get mountpoint
			MNTPT=`findmnt --source LABEL="$4" -o TARGET | sed -n -e '2p'`
			echo "$4 is mounted at ${MNTPT}"

			# if mount point is not /mnt/$4
			# then umount and mount again
			if test "${MNTPT}" != "/mnt/$4"; then
				# mounted but not at /mnt/$4
				umount "${MNTPT}"
				exitonerror $? "could not umount ${MNTPT}"
				# mount it correctly
				mount -v -L "$4" "/mnt/$4"
				exitonerror $? "could not mount $4 at /mnt/$4"
			fi
		else
			# $4 is not mounted
			mount -v -L "$4" "/mnt/$4"
			exitonerror $? "could not mount $4 at /mnt/$4"
		fi

		# remove and make the link for subversion | debhome
		rm -vf "$3"
		sudo -u $1 ln -v -s "$2" "$3"
		exitonerror $? "could not make the link $3"

		# check that the repository exists from the link
		if test -d "$3"; then
			# repository exists
			echo "repository exists at $3 -> $2"
		else
			# repository not found
			# enter a path to the repository and try again
			until test -d "$3"; do
				# prompt for a new path to $3
				echo "Enter the full path that $3 points to"
				read REPPATH
				NEWLINK="$3"
				NEWDEVICE="$4"
				# try again
				setuprepository "robert" "${REPPATH}" "${NEWLINK}" "${NEWDEVICE}"
			done

		# subversion | debhome exists and link is correct
		fi

	fi
	# repository exists
}

###
# main entry
###
setuprepository "robert" "/junk" "/mnt/debhome" "ad64"
# setuprepository "robert" "/mnt/ad64/svn" "/mnt/svn" "ad64"
